version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/js/fortune-api"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/typescript/lastfm"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/js/lastfm"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
