isGraphQL: true
schemaCheck:
  paths:
    - path: typescript/lastfm/schema.graphql
      mainBranch: master
    - path: js/fortune-api/schema.graphql
      mainBranch: master
    - path: js/lastfm/schema.graphql
      mainBranch: master
  rules:
    - FIELD_CHANGED_KIND
    - FIELD_REMOVED
    - TYPE_REMOVED
    - ARG_REMOVED
    - ARG_CHANGED_KIND
    - MISSING_TYPE_DESCRIPTION
    - MISSING_FIELD_DESCRIPTION
