env:
  es6: true
  mocha: true
  node: true
extends: "airbnb-base"
parserOptions:
  ecmaFeatures:
    modules: true
  sourceType: module
globals:
  jest: readable
  expect: readable
  executeQuery: false
rules:
  "import/no-extraneous-dependencies":
    - error
    - devDependencies: true
  generator-star-spacing: 0
  no-unused-expressions: 0
  "no-console": 0
  "newline-per-chained-call": 0
  "one-var-declaration-per-line": 0
  "no-param-reassign": 0
  "camelcase": 0
  "one-var": 0
  "max-len": 0
  "array-callback-return": 0
  "class-methods-use-this": 0
  "arrow-body-style": 1
  "func-names": 0
  "import/prefer-default-export": 0
  "no-shadow": 0
  "no-prototype-builtins": 0
  "consistent-return": 0
  "no-use-before-define": 0
  "prefer-rest-params": 0
  "no-restricted-properties": 0
