on: pull_request
name: Run Tests
jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        node_version: [14, 16]
    steps:
    - uses: actions/checkout@master
    - name: Setup Node ${{ matrix.node_version }}
      uses: actions/setup-node@v3.1.1
      with:
        node-version: ${{ matrix.node_version }}
    - name: JS Fortune Tests
      run: npm run test:jsfortune
    - name: JS Lastfm Tests
      run: npm run test:jslastfm
    - name: TS Lastfm Tests
      run: npm run test:tslastfm
