on: pull_request
name: Run Tests
jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        node_version: [10, 12]
    steps:
    - uses: actions/checkout@master
    - name: Setup Node ${{ matrix.node_version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node_version }}
    - name: JS Fortune Tests
      run: npm run test:jsfortune
    - name: JS Lastfm Tests
      run: npm run test:jslastfm
    - name: TS Lastfm Tests
      run: npm run test:tslastfm
  automerge:
    runs-on: ubuntu-latest
    needs: runTests
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
          MERGE_LABELS: "dependencies"
